// Curated Golden Boot candidate list (the free tier can't give us squads/scorers).
// It's only a suggestion list — the combobox also accepts a typed-in name.
export const GOLDEN_BOOT_CANDIDATES: { name: string; team: string }[] = [
  { name: "Kylian Mbappé", team: "France" },
  { name: "Erling Haaland", team: "Norway" },
  { name: "Harry Kane", team: "England" },
  { name: "Lionel Messi", team: "Argentina" },
  { name: "Vinícius Júnior", team: "Brazil" },
  { name: "Lautaro Martínez", team: "Argentina" },
  { name: "Julián Álvarez", team: "Argentina" },
  { name: "Cristiano Ronaldo", team: "Portugal" },
  { name: "Rafael Leão", team: "Portugal" },
  { name: "Gonçalo Ramos", team: "Portugal" },
  { name: "Lamine Yamal", team: "Spain" },
  { name: "Álvaro Morata", team: "Spain" },
  { name: "Nico Williams", team: "Spain" },
  { name: "Mohamed Salah", team: "Egypt" },
  { name: "Romelu Lukaku", team: "Belgium" },
  { name: "Kai Havertz", team: "Germany" },
  { name: "Florian Wirtz", team: "Germany" },
  { name: "Memphis Depay", team: "Netherlands" },
  { name: "Cody Gakpo", team: "Netherlands" },
  { name: "Bukayo Saka", team: "England" },
  { name: "Phil Foden", team: "England" },
  { name: "Raphinha", team: "Brazil" },
  { name: "Rodrygo", team: "Brazil" },
  { name: "Endrick", team: "Brazil" },
  { name: "Ousmane Dembélé", team: "France" },
  { name: "Darwin Núñez", team: "Uruguay" },
  { name: "Federico Valverde", team: "Uruguay" },
  { name: "Luis Díaz", team: "Colombia" },
  { name: "Son Heung-min", team: "South Korea" },
  { name: "Kaoru Mitoma", team: "Japan" },
  { name: "Takefusa Kubo", team: "Japan" },
  { name: "Christian Pulisic", team: "USA" },
  { name: "Folarin Balogun", team: "USA" },
  { name: "Jonathan David", team: "Canada" },
  { name: "Santiago Giménez", team: "Mexico" },
  { name: "Raúl Jiménez", team: "Mexico" },
  { name: "Mohammed Kudus", team: "Ghana" },
  { name: "Riyad Mahrez", team: "Algeria" },
  { name: "Youssef En-Nesyri", team: "Morocco" },
  { name: "Sadio Mané", team: "Senegal" },
  { name: "Nicolas Jackson", team: "Senegal" },
  { name: "Breel Embolo", team: "Switzerland" },
  { name: "Enner Valencia", team: "Ecuador" },
  { name: "Sébastien Haller", team: "Ivory Coast" },
];
